### ISSUE TITLE
Publish the index to Maven Central again?

### ISSUE THREAD

**Issue by alexarchambault** [coursier/jvm-index#277]
The index used to be published to Maven Central, see [here](https://repo1.maven.org/maven2/io/get-coursier/jvm-index/).

It might be interesting to do that again, to work around GitHub outages.

See https://github.com/com-lihaoyi/mill/pull/3716 for context

**Comment by lihaoyi** [comment]
@alexarchambault any updates here? We need this to unblock https://github.com/com-lihaoyi/mill/pull/3716

**Comment by alexarchambault** [comment]
@lihaoyi The new indices are automatically published since https://github.com/coursier/jvm-index/pull/297

I have to cut a new release of coursier that includes https://github.com/coursier/coursier/pull/3127 and https://github.com/coursier/coursier/pull/3128, in order to allow using the new index. Will do it in the afternoon, Europe time, in order to get a few more PRs in.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/jvm-index/pull/297

**Comment by lihaoyi** [comment]
ok thanks!

**Comment by alexarchambault** [comment]
FYI, I'm having issues cutting a new coursier release. Publishing with Mill now requires Java >= 11. I'd like to keep supporting Java 8, so `--release 8` needs to be passed to scalac, but this breaks access to unsupported JDK APIs (`sun.misc.{Signal, SignalHandler}` here). Just stumbled upon https://github.com/scala/bug/issues/13015 that has a workaround, I should be able to give it a try, but only in a few hours

**Comment by lihaoyi** [comment]
@alexarchambault you could use mill 0.11.12 if you want to use Java 8 i think, that should have gotten the publishign fix without the java version bump

**Comment by alexarchambault** [comment]
@lihaoyi That could have worked, yes. OTOH, it's nice to decouple the local JVM and the targeted one, so that we don't mistakenly bump the required JVM version.
